/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ResetPasswordResponseDto,
  ResetParams,
  SetPasswordResponseDto,
  SetPasswordRequestDto
} from '../petstore.schemas'



  /**
 * @summary Reset password
 */
export const reset = <TData = AxiosResponse<ResetPasswordResponseDto>>(
    params: ResetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/reset-password/reset`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Set new password
 */
export const setPassword = <TData = AxiosResponse<SetPasswordResponseDto>>(
    setPasswordRequestDto: SetPasswordRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/reset-password/set-password`,
      setPasswordRequestDto,options
    );
  }
export type ResetResult = AxiosResponse<ResetPasswordResponseDto>
export type SetPasswordResult = AxiosResponse<SetPasswordResponseDto>
