/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  MeResponseDto
} from '../petstore.schemas'



  export const me = <TData = AxiosResponse<MeResponseDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/user/me`,options
    );
  }
export type MeResult = AxiosResponse<MeResponseDto>
