/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AllResponseDto,
  TerminateResponseDto,
  TerminateRequestDto
} from '../petstore.schemas'



  export const all = <TData = AxiosResponse<AllResponseDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/session/all`,options
    );
  }
export const terminate = <TData = AxiosResponse<TerminateResponseDto>>(
    terminateRequestDto: TerminateRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/session/terminate`,
      terminateRequestDto,options
    );
  }
export const terminateAll = <TData = AxiosResponse<TerminateResponseDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/session/terminate-all`,undefined,options
    );
  }
export type AllResult = AxiosResponse<AllResponseDto[]>
export type TerminateResult = AxiosResponse<TerminateResponseDto>
export type TerminateAllResult = AxiosResponse<TerminateResponseDto>
