/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreateTransactionResponseDto,
  CreateTransactionRequestDto,
  GetTransactionsResponseDto,
  GetTransactionByIdResponseDto,
  UpdateTransactionByIdResponseDto,
  UpdateTransactionByIdRequestDto,
  DeleteTransactionByIdResponseDto,
  GetTransactionsByAccountResponseDto
} from '../petstore.schemas'



  export const create = <TData = AxiosResponse<CreateTransactionResponseDto>>(
    createTransactionRequestDto: CreateTransactionRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/transactions/create`,
      createTransactionRequestDto,options
    );
  }
export const get = <TData = AxiosResponse<GetTransactionsResponseDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/transactions/get`,options
    );
  }
export const getById = <TData = AxiosResponse<GetTransactionByIdResponseDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/transactions/${id}`,options
    );
  }
export const updateById = <TData = AxiosResponse<UpdateTransactionByIdResponseDto>>(
    id: number,
    updateTransactionByIdRequestDto: UpdateTransactionByIdRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/transactions/${id}`,
      updateTransactionByIdRequestDto,options
    );
  }
export const deleteById = <TData = AxiosResponse<DeleteTransactionByIdResponseDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/transactions/${id}`,options
    );
  }
export const getTransactionsByAccount = <TData = AxiosResponse<GetTransactionsByAccountResponseDto>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/transactions/account/${id}`,options
    );
  }
export type CreateResult = AxiosResponse<CreateTransactionResponseDto>
export type GetResult = AxiosResponse<GetTransactionsResponseDto[]>
export type GetByIdResult = AxiosResponse<GetTransactionByIdResponseDto>
export type UpdateByIdResult = AxiosResponse<UpdateTransactionByIdResponseDto>
export type DeleteByIdResult = AxiosResponse<DeleteTransactionByIdResponseDto>
export type GetTransactionsByAccountResult = AxiosResponse<GetTransactionsByAccountResponseDto>
