/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  VerifyResponseDto,
  VerifyRequestDto
} from '../petstore.schemas'



  /**
 * @summary Verify email
 */
export const verify = <TData = AxiosResponse<VerifyResponseDto>>(
    verifyRequestDto: VerifyRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/email-verification/verify`,
      verifyRequestDto,options
    );
  }
/**
 * @summary Resend verification link
 */
export const resend = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/email-verification/resend`,undefined,options
    );
  }
export type VerifyResult = AxiosResponse<VerifyResponseDto>
export type ResendResult = AxiosResponse<unknown>
