/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  SignUpResponseDto,
  SignUpRequestDto,
  SignInResponseDto,
  SignInRequestDto,
  RefreshTokenResponseDto,
  SignOutResponseDto
} from '../petstore.schemas'



  /**
 * @summary Sign up
 */
export const signUp = <TData = AxiosResponse<SignUpResponseDto>>(
    signUpRequestDto: SignUpRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/sign-up`,
      signUpRequestDto,options
    );
  }
/**
 * @summary Sign in
 */
export const signIn = <TData = AxiosResponse<SignInResponseDto>>(
    signInRequestDto: SignInRequestDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/sign-in`,
      signInRequestDto,options
    );
  }
/**
 * @summary Refresh access token
 */
export const refresh = <TData = AxiosResponse<RefreshTokenResponseDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/refresh`,undefined,options
    );
  }
/**
 * @summary Sign out
 */
export const signOut = <TData = AxiosResponse<SignOutResponseDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/sign-out`,undefined,options
    );
  }
export type SignUpResult = AxiosResponse<SignUpResponseDto>
export type SignInResult = AxiosResponse<SignInResponseDto>
export type RefreshResult = AxiosResponse<RefreshTokenResponseDto>
export type SignOutResult = AxiosResponse<SignOutResponseDto>
